export let modifiedData = 
[
  {
    "_id": "62398b64d88fa52c19eb4629",
    "index": 0,
    "name": "Riddle Cohen",
    "Category": "Others",
    "shortText": "cillum fugiat s est",
    "longText": "consequat dolor excepteur excepteur aliqua cupidatat dolor pariatur duis labore sint deserunt sint commodo amet consequat dolor excepteur except",
    "numbers": 48,
    "percentage": 0.25,
    "dates": new Date("01/02/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=6",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 1000.99,
  },
  {
    "_id": "62398b64e1c89606a1cf3da5",
    "index": 1,
    "name": "Maricela Kane",
    "Category": "Others",
    "shortText": "consequat enim et ficia",
    "longText": "tempor minim fugiat nisi enim consectetur nisi aliqua est sit commodo esse incididunt magna voluptate",
    "numbers": 58,
    "percentage": 0.49,
    "dates": new Date("04/01/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=3",
    "font": "pi pi-thumbs-down jordDanger",
    "price": 1111.11,
  },
  {
    "_id": "62398b64568de73d20075e22",
    "index": 2,
    "name": "Felecia Thompson",
    "Category": "Monitor",
    "shortText": "anim nisi  sint",
    "longText": "veniam culpa ullamco aute aliquip non ea ut commodo velit id ut Lorem labore eu",
    "numbers": 8,
    "percentage": 0.5,
    "dates": new Date("02/28/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=30",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 999999999.00,
  },
  {
    "_id": "62398b6408d6d0108a982435",
    "index": 3,
    "name": "Reyna Weeks",
    "Category": "Laptop",
    "shortText": "anim ullamco s sit",
    "longText": "quis amet veniam et culpa quis velit aliquip duis enim cillum labore velit ipsum ut",
    "numbers": 39,
    "percentage": 0.75,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=62",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b642e97e0431e33eb95",
    "index": 4,
    "name": "Serrano Richmond",
    "Category": "Others",
    "shortText": "labore fugiat  sunt",
    "longText": "exercitation eiusmod qui consequat consectetur sit nostrud exercitation quis exercitation magna ipsum eiusmod laborum cupidatat",
    "numbers": 25,
    "percentage": 0.58,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=16",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b64219995daf10c1778",
    "index": 5,
    "name": "Madeline Burns",
    "Category": "Tablet",
    "shortText": "enim laboris it ex",
    "longText": "voluptate sit laboris voluptate non exercitation duis adipisicing reprehenderit dolor laboris est aliqua fugiat pariatur",
    "numbers": 40,
    "percentage": 0.79,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=96",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64c416bed2f94d7e19",
    "index": 6,
    "name": "Aida Hurst",
    "Category": "Tablet",
    "shortText": "cillum voluptate  sunt",
    "longText": "qui excepteur reprehenderit fugiat minim non officia irure exercitation quis commodo minim aute reprehenderit cillum",
    "numbers": 32,
    "percentage": 0.77,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=8",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b6486aa5aef3a489549",
    "index": 7,
    "name": "Miriam Chapman",
    "Category": "Monitor",
    "shortText": "aliquip est  sunt",
    "longText": "eu cupidatat Lorem fugiat irure enim aliqua dolore amet ut laboris enim ipsum consequat laboris",
    "numbers": 12,
    "percentage": 0.7,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=78",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b645b22523119a412d5",
    "index": 8,
    "name": "Ramsey Ross",
    "Category": "Laptop",
    "shortText": "labore incididunt elit pteur",
    "longText": "mollit reprehenderit veniam irure quis ut voluptate ex aliquip sit cillum ex ut officia eu",
    "numbers": 56,
    "percentage": 0.43,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=19",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64e6d0dcdd1e8f86d7",
    "index": 9,
    "name": "Howard Jackson",
    "Category": "Tablet",
    "shortText": "quis cupidatat velit",
    "longText": "mollit irure aliquip eiusmod laboris proident consequat eiusmod laborum aute excepteur esse laboris reprehenderit non",
    "numbers": 35,
    "percentage": 0.31,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=2",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b646807d20c4968dced",
    "index": 10,
    "name": "Katrina Burke",
    "Category": "Tablet",
    "shortText": "et incididunt nostrud ation",
    "longText": "consectetur esse aliqua nostrud commodo ad non fugiat quis nostrud in veniam velit irure sunt",
    "numbers": 84,
    "percentage": 0.48,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=19",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b6469ae0552891d8c04",
    "index": 11,
    "name": "Eva Bender",
    "Category": "Others",
    "shortText": "occaecat dolore a non",
    "longText": "aliquip labore aliqua nostrud labore labore consequat ut in aliquip excepteur id veniam in irure",
    "numbers": 63,
    "percentage": 0.90,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=10",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64d4f28e788e0ef888",
    "index": 12,
    "name": "Christensen Campos",
    "Category": "Monitor",
    "shortText": "do dolor velit ation",
    "longText": "sunt aliqua ea est nostrud mollit nostrud est excepteur id nisi elit voluptate ea reprehenderit",
    "numbers": 64,
    "percentage": 0.20,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=37",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b648396547a8403e031",
    "index": 13,
    "name": "Hess Webb",
    "Category": "Monitor",
    "shortText": "incididunt esse cupidatat tetur",
    "longText": "consectetur reprehenderit occaecat ipsum elit aute veniam nisi minim aliqua velit qui non excepteur in",
    "numbers": 74,
    "percentage": 0.49,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=71",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b6490f30f2df45ab70c",
    "index": 14,
    "name": "Christy French",
    "Category": "Others",
    "shortText": "occaecat adipisicing anim iatur",
    "longText": "mollit aliqua ex aliqua ipsum excepteur cillum occaecat elit consectetur tempor cillum ipsum ullamco id",
    "numbers": 23,
    "percentage": 0.46,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=57",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b644d3b38ad525db2f9",
    "index": 15,
    "name": "Sweet Buck",
    "Category": "Monitor",
    "shortText": "ea id culpa pteur",
    "longText": "nulla eiusmod do magna veniam quis labore pariatur elit minim officia sunt occaecat incididunt occaecat",
    "numbers": 69,
    "percentage": 0.97,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=56",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b64930bbe13bd59278d",
    "index": 16,
    "name": "Jewell Hood",
    "Category": "Monitor",
    "shortText": "qui non incididunt iatur",
    "longText": "commodo amet deserunt do Lorem nisi tempor in quis reprehenderit ex sit pariatur eu eu",
    "numbers": 54,
    "percentage": 0.47,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=33",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b6481df1488187e3e40",
    "index": 17,
    "name": "Ramirez Price",
    "Category": "Monitor",
    "shortText": "consequat Lorem  amet",
    "longText": "quis ut non Lorem anim irure eiusmod minim do consectetur eu esse nostrud consequat amet",
    "numbers": 0,
    "percentage": 0.24,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=60",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64f058bbb0566b3365",
    "index": 18,
    "name": "Jenny Tran",
    "Category": "Tablet",
    "shortText": "labore sint velit",
    "longText": "excepteur irure dolor sunt occaecat incididunt officia consequat irure laborum laboris sunt nostrud qui velit",
    "numbers": 66,
    "percentage": 0.99,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=24",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b6421119d060a63b2d7",
    "index": 19,
    "name": "Amie Gray",
    "Category": "Laptop",
    "shortText": "in ad s sit",
    "longText": "adipisicing excepteur adipisicing irure laborum excepteur culpa culpa magna duis sunt ullamco minim duis proident",
    "numbers": 11,
    "percentage": 0.79,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=23",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b647649cd7bd6eadd90",
    "index": 20,
    "name": "Lowery Ferrell",
    "Category": "Monitor",
    "shortText": "ad laborum a sit",
    "longText": "officia ipsum mollit pariatur ex ea ullamco consequat sit esse cillum in voluptate magna dolore",
    "numbers": 69,
    "percentage": 0.9,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=45",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b6410c6d60063d0cb01",
    "index": 21,
    "name": "Lee Craig",
    "Category": "Laptop",
    "shortText": "sunt in labore erunt",
    "longText": "irure incididunt minim ullamco fugiat commodo do duis et culpa laboris do ut velit do",
    "numbers": 34,
    "percentage": 0.14,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=59",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64054c3afc483a2109",
    "index": 22,
    "name": "Dina Randolph",
    "Category": "Tablet",
    "shortText": "aliquip excepteur  elit",
    "longText": "aliquip do duis exercitation sunt aute eu excepteur do proident aliquip tempor exercitation est dolor",
    "numbers": 17,
    "percentage": 0.68,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=17",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64688abcfe8c590b7f",
    "index": 23,
    "name": "Vincent Sweeney",
    "Category": "Monitor",
    "shortText": "cillum ex liqua",
    "longText": "deserunt non commodo aute esse sint culpa anim adipisicing qui proident enim do mollit aliquip",
    "numbers": 58,
    "percentage": 0.87,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=34",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b64a214dd676c15dea4",
    "index": 24,
    "name": "Rose Mason",
    "Category": "Laptop",
    "shortText": "proident qui at ad",
    "longText": "cupidatat nisi tempor laboris est incididunt consectetur ipsum quis duis laborum ipsum sunt dolor excepteur",
    "numbers": 86,
    "percentage": 0.87,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=75",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b6467255160a2d66af1",
    "index": 25,
    "name": "Bobbi Harper",
    "Category": "Monitor",
    "shortText": "cupidatat laborum minim",
    "longText": "duis ad occaecat voluptate pariatur commodo qui reprehenderit elit reprehenderit tempor consequat qui sint dolore",
    "numbers": 79,
    "percentage": 0.72,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=20",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b64c55df7daa3e6d0d7",
    "index": 26,
    "name": "Greene Pearson",
    "Category": "Laptop",
    "shortText": "culpa aute illum",
    "longText": "eiusmod minim commodo reprehenderit mollit aliquip culpa consectetur commodo sint reprehenderit quis pariatur ullamco voluptate",
    "numbers": 98,
    "percentage": 0.69,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=64",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64cf0388fae8d3a30d",
    "index": 27,
    "name": "Franks Stephenson",
    "Category": "Laptop",
    "shortText": "consectetur aute  nisi",
    "longText": "officia ex voluptate duis in reprehenderit ullamco eiusmod ut et id sit magna in laboris",
    "numbers": 71,
    "percentage": 0.93,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=84",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64526ab03e23133b6e",
    "index": 28,
    "name": "Haley Summers",
    "Category": "Laptop",
    "shortText": "irure occaecat cillum ation",
    "longText": "sunt tempor anim esse occaecat consectetur laborum sint cupidatat ullamco exercitation nostrud sunt laborum cupidatat",
    "numbers": 43,
    "percentage": 0.17,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=94",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b64a8bb9b9ce67c4f57",
    "index": 29,
    "name": "Bridget Sherman",
    "Category": "Laptop",
    "shortText": "nostrud laboris  anim",
    "longText": "laboris ad ut commodo elit id ullamco excepteur pariatur mollit elit amet ad sit laboris",
    "numbers": 88,
    "percentage": 0.10,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=92",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64710f322a15bf3a29",
    "index": 30,
    "name": "Rodriguez Morton",
    "Category": "Tablet",
    "shortText": "ea duis mollit idunt",
    "longText": "anim cupidatat reprehenderit voluptate reprehenderit adipisicing labore culpa aute proident adipisicing consectetur est tempor ullamco",
    "numbers": 61,
    "percentage": 0.18,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=81",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64d358e6f8b4ae2746",
    "index": 31,
    "name": "Vance Villarreal",
    "Category": "Monitor",
    "shortText": "aute nostrud  elit",
    "longText": "deserunt amet minim cillum ea aute laborum aute dolor do duis incididunt elit duis Lorem",
    "numbers": 84,
    "percentage": 0.22,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=60",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b6475eadfa074f2a6b9",
    "index": 32,
    "name": "Kramer Lucas",
    "Category": "Monitor",
    "shortText": "dolor anim liqua",
    "longText": "reprehenderit mollit ad reprehenderit officia cillum culpa dolore dolore cillum quis cupidatat laborum et irure",
    "numbers": 72,
    "percentage": 0.78,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=17",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64c94df9bae126030e",
    "index": 33,
    "name": "Hamilton Hinton",
    "Category": "Monitor",
    "shortText": "excepteur mollit m sit",
    "longText": "aliqua labore enim pariatur nostrud veniam minim dolore deserunt laborum laborum sint aliqua do pariatur",
    "numbers": 57,
    "percentage": 0.53,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=24",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b640860a0410b332299",
    "index": 34,
    "name": "Kitty Leonard",
    "Category": "Laptop",
    "shortText": "velit in do",
    "longText": "velit irure proident proident laboris amet occaecat eiusmod consectetur ad id in est commodo consectetur",
    "numbers": 20,
    "percentage": 0.61,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=88",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b649abbad8bf2335b23",
    "index": 35,
    "name": "Daisy Ellison",
    "Category": "Monitor",
    "shortText": "amet dolor empor",
    "longText": "voluptate laborum nostrud magna laboris sit qui commodo commodo ad enim nostrud ut occaecat excepteur",
    "numbers": 31,
    "percentage": 0.37,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=82",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b6427a8fa51780b62f3",
    "index": 36,
    "name": "Solis Moody",
    "Category": "Tablet",
    "shortText": "proident sit irure",
    "longText": "qui fugiat mollit incididunt ut eu exercitation et nostrud eiusmod magna laborum tempor excepteur ipsum",
    "numbers": 42,
    "percentage": 0.77,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=68",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b64ed6c1f70988cd7c9",
    "index": 37,
    "name": "Kim Hogan",
    "Category": "Laptop",
    "shortText": "reprehenderit ex deserunt pteur",
    "longText": "amet deserunt quis adipisicing fugiat id commodo amet nulla minim tempor aliqua anim deserunt nulla",
    "numbers": 65,
    "percentage": 0.26,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=80",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b647975c5f3935ca62e",
    "index": 38,
    "name": "Mia Williams",
    "Category": "Others",
    "shortText": "ullamco exercitation sunt ptate",
    "longText": "fugiat aliquip ad ex et occaecat cillum ipsum qui aliquip proident mollit quis laborum esse",
    "numbers": 32,
    "percentage": 0.71,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=81",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b640e6dd4659a906baf",
    "index": 39,
    "name": "Rosario Cotton",
    "Category": "Laptop",
    "shortText": "sint officia  duis",
    "longText": "voluptate enim ut tempor enim proident sint sit irure exercitation esse excepteur excepteur mollit cupidatat",
    "numbers": 19,
    "percentage": 0.30,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=35",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b6450fca61ab467f920",
    "index": 40,
    "name": "Leann Stafford",
    "Category": "Others",
    "shortText": "velit nostrud nulla",
    "longText": "in sint occaecat ut voluptate est duis qui ut est consectetur voluptate eiusmod dolore in",
    "numbers": 3,
    "percentage": 0.90,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=37",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b649942320d1e9da767",
    "index": 41,
    "name": "Eileen Cooley",
    "Category": "Others",
    "shortText": "in et dolor",
    "longText": "dolor deserunt fugiat tempor irure excepteur exercitation et dolor ea Lorem do voluptate duis dolore",
    "numbers": 57,
    "percentage": 0.18,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=100",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64dce68fe6e3335edf",
    "index": 42,
    "name": "Polly Burks",
    "Category": "Others",
    "shortText": "occaecat reprehenderit Lorem aecat",
    "longText": "velit anim reprehenderit dolore exercitation exercitation ea deserunt laboris incididunt commodo minim eu ex fugiat",
    "numbers": 59,
    "percentage": 0.4,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=45",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b64bbe85704c8ad1689",
    "index": 43,
    "name": "Stewart Gutierrez",
    "Category": "Others",
    "shortText": "commodo dolore deserunt idunt",
    "longText": "elit ullamco eu est duis irure est excepteur aute consectetur proident aliquip dolore culpa fugiat",
    "numbers": 67,
    "percentage": 0.84,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=66",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b648b4727f1c78697db",
    "index": 44,
    "name": "Salas Wilkins",
    "Category": "Others",
    "shortText": "irure non ng id",
    "longText": "dolore culpa labore tempor qui ea tempor nostrud eiusmod ad consectetur est ex pariatur veniam",
    "numbers": 62,
    "percentage": 0.15,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=25",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b643e723693122378c9",
    "index": 45,
    "name": "Carole Carroll",
    "Category": "Laptop",
    "shortText": "culpa anim it do",
    "longText": "deserunt labore ad Lorem ut quis aliquip irure aliqua ullamco aute ullamco aute qui ea",
    "numbers": 72,
    "percentage": 0.49,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=73",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b64c85db7552e2b3e69",
    "index": 46,
    "name": "Meagan Torres",
    "Category": "Tablet",
    "shortText": "dolor reprehenderit um et",
    "longText": "incididunt voluptate reprehenderit occaecat anim occaecat cupidatat excepteur esse et irure sint commodo occaecat dolore",
    "numbers": 15,
    "percentage": 0.2,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=83",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b64ac0436d36de6889d",
    "index": 47,
    "name": "Staci Vega",
    "Category": "Laptop",
    "shortText": "cupidatat sit  duis",
    "longText": "ipsum sint eu velit cillum do exercitation voluptate quis anim qui Lorem labore est exercitation",
    "numbers": 13,
    "percentage": 0.70,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=37",
    "font": "pi pi-send",
    "price": 2000.00,
  },
  {
    "_id": "62398b640df9b3191d336bc3",
    "index": 48,
    "name": "Lila Martinez",
    "Category": "Laptop",
    "shortText": "sit quis fugiat erunt",
    "longText": "magna culpa mollit in adipisicing sint magna ex incididunt tempor pariatur ullamco labore amet sit",
    "numbers": 15,
    "percentage": 0.73,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=21",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  },
  {
    "_id": "62398b6406c0795443a78598",
    "index": 49,
    "name": "Hensley York",
    "Category": "Monitor",
    "shortText": "minim nostrud dolor",
    "longText": "duis cupidatat esse duis minim exercitation minim dolore dolor cupidatat excepteur aliquip tempor duis magna",
    "numbers": 14,
    "percentage": 0.32,
    "dates": new Date("03/23/2022"),
    "photos": "https://source.unsplash.com/random/300x200?sig=47",
    "font": "pi pi-thumbs-up jordSuccess",
    "price": 2000.00,
  }
]